version: "3"
services:
  database:
    image: mysql
    container_name: wanted_db
    environment:
      - MYSQL_DATABASE=wanted_db
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3309:3306
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - wanted_db
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - 8081:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/wanted_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - wanted_db
    container_name: wanted_db_app

networks:
  wanted_db: